<?php include $phireHeader; ?>
<?php if ($acl->isAllowed($user->role, 'themes', 'install')): ?>
    <form id="asset-upload-form" action="<?=$phireUri . '/themes/upload'; ?>" method="post" enctype="multipart/form-data">
        <div><input tabindex="2" type="submit" id="submit" value="Upload" /></div>
        <div><input tabindex="1" type="file" name="upload_theme" id="upload_theme" required="required" value="" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="themes-header"><?=$title; ?></h1>
<?php if ((($newThemes > 0) || ($newChildren > 0)) && ($acl->isAllowed($user->role, 'themes', 'install'))): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/themes/install'; ?>">Install (<?=$newThemes + $newChildren; ?>)</a></nav>
    </nav>
<?php endif; ?>
<?php if (count($themes) > 0): ?>
<?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?>
    <form id="themes-form" action="<?=$phireUri . '/themes/process'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/themes?sort=id';?>">#</a></th>
                <th>Screenshot</th>
                <th><a href="<?=$phireUri . '/themes?sort=name';?>">Name</a></th>
                <th>Version</th>
                <th>Description</th>
                <th>Author</th>
                <th>Installed</th>
                <th>Updated</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?><a href="<?=$phireUri . '/themes?sort=active';?>">Active</a><?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_themes" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($themes as $theme): ?>
<?php
    $assets        = unserialize($theme->assets);
    $activeChecked = ($theme->active)  ? ' checked="checked"' : null;
?>
            <tr>
                <td><?=$theme->id; ?></td>
                <td><?=$theme->screenshot; ?></td>
                <td><?=(isset($assets['info']['Theme Name']) ? $assets['info']['Theme Name'] : '&nbsp;'); ?></td>
                <td><?=$theme->version; ?><?php if ($acl->isAllowed($user->role, 'themes', 'update') && isset($themeUpdates) && isset($themeUpdates[$theme->name]) && (version_compare($theme->version, $themeUpdates[$theme->name]) < 0)):
    echo ' (<a class="normal-link" href="' . $phireUri . '/themes/update/' . $theme->id .  '">Update to ' . $themeUpdates[$theme->name] . '</a>)';
endif; ?></td>
                <td><?=(isset($assets['info']['Description']) ? $assets['info']['Description'] : '&nbsp;'); ?></td>
                <td><?=(isset($assets['info']['Author']) ? $assets['info']['Author'] : '&nbsp;'); ?></td>
                <td><?=date($config->datetime_format, strtotime($theme->installed_on)); ?></td>
                <td><?=((null !== $theme->updated_on) ? date($config->datetime_format, strtotime($theme->updated_on)) : '&nbsp;'); ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?><input type="radio" name="active" value="<?=$theme->id; ?>" <?=$activeChecked; ?>/><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?><input type="checkbox" name="rm_themes[]" id="rm_themes<?=$i++; ?>" value="<?=$theme->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'themes', 'process')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no themes.<?php if (($newThemes > 0) && ($acl->isAllowed($user->role, 'themes', 'install'))): ?> New themes have been detected. Click the install button above to install them.<?php endif; ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>
